#!/bin/bash
sudo apt-get install nginx -y
sudo add-apt-repository ppa:ondrej/php -y
sudo apt-get update
sudo apt-get install python-software-properties -y
sudo apt-get update
sudo apt-get install php7.0-fpm php7.0-intl php7.0-imap php7.0-mongo php7.0-gd php7.0-curl php7.0-mysql php7.0-mcrypt php7.0-mbstring php7.0-zip php7.0-xml php7.0-soap -y
php -v
