#!/bin/bash
rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-6.noarch.rpm
rpm -Uvh https://mirror.webtatic.com/yum/el6/latest.rpm

yum install php70w php70w-opcache php70w-fpm php70w-intl php70w-imap php70w-mongo php70w-gd php70w-curl php70w-mysql php70w-mcrypt php70w-mbstring php70w-zip php70w-xml php70w-soap php70w-bcmath -y
