#!/bin/bash
sudo apt-get install nginx -y
sudo add-apt-repository ppa:ondrej/php -y
sudo apt-get update
sudo apt-get install python-software-properties -y
sudo apt-get update
sudo apt-get install php7.1-fpm php7.1-intl php7.1-imap php7.1-mongo php7.1-gd php7.1-curl php7.1-mysql php7.1-mcrypt php7.1-mbstring php7.1-zip php7.1-xml php7.1-soap php7.1-bcmath -y
php -v
