#!/bin/bash
sudo apt-get install nginx
sudo add-apt-repository ppa:ondrej/php5-5.6
sudo apt-get update
sudo apt-get install python-software-properties
sudo apt-get update
sudo apt-get install php5-fpm php5-intl php5-imap php5-mongo php5-gd php5-curl php5-mysql php5-mcrypt php5-mbstring php5-zip
php5 -v
