#!/bin/bash
sudo apt-get install nginx
sudo add-apt-repository ppa:ondrej/php
sudo apt-get update
sudo apt-get install python-software-properties
sudo apt-get update
sudo apt-get install php5.6-fpm php5.6-intl php5.6-imap php5.6-mongo php5.6-gd php5.6-curl php5.6-mysql php5.6-mcrypt php5.6-mbstring php5.6-zip php5.6-xml
php5 -v
