#!/bin/bash
sudo apt-get update
sudo apt-get install git -y
cd ~/
git clone https://github.com/RubenHarms/serverDeploy.git ~/serverDeploy
cd ~/serverDeploy/majesticInstance
chmod +x install
./install
