#!/usr/bin/env bash

pushd `dirname $0` > /dev/null
CURRENT_PATH=`pwd -P`
popd > /dev/null

. ${CURRENT_PATH}/../include/main

rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
rpm -Uvh https://mirror.webtatic.com/yum/el7/webtatic-release.rpm
sudo yum install epel-release

yum -y remove httpd
yum install nginx -y
rm /etc/nginx/nginx.conf -f
cp ~/serverDeploy/majesticInstance/nginx.conf /etc/nginx/nginx.conf
yum -y install net-tools
yum -y groupinstall 'Development Tools'
yum  -y install nano php56w-common php56w-opcache php56w-intl php56w-imap php56w-mongo php56w-gd php56w-curl php56w-mysql php56w-fpm php56w-mbstring openssl openssl-devel php56w-pear php56w-devel php56w-mcrypt php56w-soap php56w-bcmath &&
pecl install mongo
echo "" >> /etc/php.ini
echo "extension=mongo.so" >> /etc/php.ini
php -v

mkdir -p /var/www/domains/majesticproxy
chown nginx.nginx /var/www/domains/majesticproxy

cd ~/
git clone https://github.com/MajesticSender/majesticProxy.git
cp ~/serverDeploy/majesticInstance/majesticproxy.loc.conf /etc/nginx/conf.d/majesticproxy.conf
cp ./majesticProxy/app.php /var/www/domains/majesticproxy
rm  /etc/php-fpm.d/www.conf -f
cp ~/serverDeploy/majesticInstance/www.conf /etc/php-fpm.d/www.conf

service nginx restart &&
service php-fpm restart &&

systemctl enable nginx &&
systemctl enable php-fpm &&
systemctl disable iptables &&
systemctl stop iptables &&

yum install exim dovecot -y &&

rm /etc/dovecot/dovecot.conf -f
rm /etc/exim/exim.conf -f
rm /etc/dovecot/conf.d/10-master.conf -f

cp  ~/serverDeploy/majesticInstance/10-master.conf /etc/dovecot/conf.d/10-master.conf
cp  ~/serverDeploy/majesticInstance/dovecot.conf /etc/dovecot/dovecot.conf
cp  ~/serverDeploy/majesticInstance/exim.conf /etc/exim/exim.conf

openssl genrsa -out /etc/exim/dkim.private.key 1024 
openssl rsa -in /etc/exim/dkim.private.key -out /etc/exim/dkim.public.key -pubout -outform PEM 

mkdir /etc/virtual
touch /etc/virtual/domains
touch /etc/virtual/hosts

systemctl enable exim &&
systemctl restart exim &&

systemctl enable dovecot &&
systemctl restart dovecot &&

groupadd vmail
useradd vmail -g mail -d /home/vmail
