#!/bin/bash
sudo yum update -y
sudo yum install git -y
git clone https://github.com/RubenHarms/serverDeploy.git ~/serverDeploy
cd ~/serverDeploy/majesticInstance
chmod +x installCentOs
./installCentOs
