#!/bin/bash

. ../include/os.sh

echo $OS;


NAMES=()
USERS=()
REPOSITORIES=()
FOLDERS=()

function addSoftware () {
    NAMES+=("$1")
    USERS+=("$2")
    REPOSITORIES+=("$3")
    FOLDERS+=("$4")
}

function showSoftware (){
    for ((i = 0; i < ${#NAMES[@]}; i++))
    do
        echo  "$i: ${NAMES[$i]}"
    done
}

function getArrayArguments () {
     a=("$@");

     argumentsFrom=""
     array=()
     arrayPointer=0
     for ((i = 0; i < ${#a[@]}; i++))
     do
         if [ $i = 0 ]; then
            let argumentsFrom=${a[0]}-1
         else
             if [ $i -gt $argumentsFrom ]; then
                array[$arrayPointer]="${a[$i]}"
                arrayPointer+=1
             fi
         fi
     done

     echo "${array[@]}"
}

function askQuestion(){

    #echo $@
    question=$2
    type=$1
    default=$3
    choices=($(getArrayArguments 4 "$@"))

    while true; do
        echo -n "${question} [${default}]: ";
        read input
        if [ "${type}" = "number" ]; then
            re='^[0-9]+$'
            if [[ $input =~ $re ]] ; then
                lastInput=$input
                break
            fi
        elif [ "${type}" = "choices" ]; then
            if [[ "${#choices[$input]}" -ne 0 ]]; then
                lastInput=$input;
                break
            fi
        fi
    done

}


addSoftware 'MajesticSender' 'majesticsender' 'git@git.e-vence.nl:rsa/MajesticSender.git' 'majesticsender'
addSoftware 'RSA Leads' 'rsaleads' 'git@git.e-vence.nl:rsa/RsaLeads.git' 'rsaleads'

echo "The following software is available: ";
showSoftware

askQuestion choices "Which software do you want to install?" 0 "${USERS[@]}"

dir=${FOLDERS[$lastInput]}
user=${USERS[$lastInput]}
repository=${REPOSITORIES[$lastInput]}



exit;

sudo mkdir /var/www/domains/${dir} --parents;

php -r "readfile('https://getcomposer.org/installer');" > composer-setup.php
sudo php composer-setup.php --install-dir=/usr/bin/
sudo mv /usr/bin/composer.phar /usr/bin/composer 
php -r "unlink('composer-setup.php');"

ssh-keygen -t rsa -C "postbus@rubenharms.nl"
cat ~/.ssh/id_rsa.pub

echo "Add the key above to de chain of the repository from Majestic sender and press [ENTER] to continue: "
read continue;

git clone ${repository} /var/www/domains/${dir}
sudo groupadd $user
sudo useradd $user -g $user -d /var/www/domains/${dir};
chown ${user}.${user} /var/www/domains/${dir}  -R

if [ OS = "Ubuntu" ]; then
    sudo apt-get install nodejs npm
elif [ OS = "RedHat" ]; then
    yum -y install nodejs npm
fi

sudo npm install -g uglify-js
sudo npm install -g uglifycss

cd /var/www/domains/majesticsender/
php -d memory_limit=-1 /usr/bin/composer update
