#!/bin/sh
# Steps to make new mail user:

read -p " Enter user's domain: " domain
read -p " Enter user's username: " username
read -sp " Enter password: " passwd

mkdir /home/vmail/$username@$domain
chown vmail:vmail /home/vmail/$username@$domain
chmod go-rwx /home/vmail/$username@$domain
echo $domain >> /etc/virtual/domains
echo $username@$domain:`doveadm pw -s crypt -p $passwd` >> /etc/dovecot/imap.passwd
echo `htpasswd -nb $username@$domain $passwd` >> /etc/exim/passwd
