#!/usr/bin/env bash

pushd `dirname $0` > /dev/null
CURRENT_PATH=`pwd -P`
popd > /dev/null

. ${CURRENT_PATH}/../include/main

NEWLINE=$'\n'
dnsTemplate=""
reversedDns=""
spfRecord=""
ipadress=(`hostname -I`)
alphabeth=( 0 a b c d e f g h i j k l m n o p q r s t u v w x y z)

rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm
rpm -Uvh https://mirror.webtatic.com/yum/el7/webtatic-release.rpm
sudo yum install epel-release

yum -y install net-tools
yum -y groupinstall 'Development Tools'

systemctl disable iptables
systemctl stop iptables


echo -n "Vul het toplevel domeinnaam in [mxcompute.com]: "
read toplevel

if [ -z "$toplevel" ]
then
	toplevel="mxcompute.com"
fi;

echo -n "Vul de naam van de server in (bijvoorbeeld s1): "
read servername

hostname="${servername}.${toplevel}"

hostnamectl set-hostname $hostname
hostnamectl status
systemctl restart systemd-hostnamed

yum install exim dovecot -y

rm /etc/dovecot/dovecot.conf -f
rm /etc/exim/exim.conf -f
rm /etc/dovecot/conf.d/10-master.conf -f

cp  ~/serverDeploy/majesticInstance/10-master.conf /etc/dovecot/conf.d/10-master.conf
cp  ~/serverDeploy/majesticInstance/dovecot.conf /etc/dovecot/dovecot.conf
cp  ~/serverDeploy/majesticInstance/exim.conf /etc/exim/exim.conf


for ((i = 0; i < ${#ipadress[@]}; i++))
do
 ip=${ipadress[i]};
 if [ "$ip" != "127.0.0.1" ] 
 then
	dnsTemplate="${dnsTemplate}${NEWLINE}${servername}${alphabeth[i]}	IN	A	${ip}"
	reversedDns="${reversedDns}${NEWLINE}${ip}: ${servername}${alphabeth[i]}.${toplevel}"
	spfRecord="${spfRecord} ip4:${ip}"
 fi
done

openssl genrsa -out /etc/exim/dkim.private.key 1024 
openssl rsa -in /etc/exim/dkim.private.key -out /etc/exim/dkim.public.key -pubout -outform PEM 

mkdir /etc/virtual
touch /etc/virtual/domains
touch /etc/virtual/hosts
touch /etc/dovecot/imap.passwd

systemctl enable exim
systemctl restart exim

systemctl enable dovecot
systemctl restart dovecot

groupadd vmail
useradd vmail -g vmail -d /home/vmail
chown vmail.mail /var/mail/
usermod -a -G vmail exim
chmod 750 /home/vmail/

cd ~/
git clone http://git.e-vence.nl/rsa/serverAPI.git
cd serverAPI/
./install.sh

echo "Your public key is:"
cat /etc/exim/dkim.public.key


dns='"'"v=DKIM1; p="'"'

while read line; do # 'line' is the variable name
        if [ -z "$(echo "$line" | egrep 'BEGIN|END')" ]
        then
            	dns="${dns} "'"'"${line}"'"'
        fi
done < /etc/exim/dkim.public.key



echo "Add the following records to the DNS of ${toplevel}:"
echo "---------------------------------------"
echo "$dnsTemplate"
echo "---------------------------------------"
echo ""


echo "Add the following record to each sender domain: "
echo "---------------------------------------"
echo  "${servername}._domainkey	IN      TXT       ${dns}"
echo "---------------------------------------"

echo -n "Vul het txt record domeinnaam in [correo.mxcompute.com]: "
read txtRecord
if [ -z "$txtRecord" ]
then
	txtRecord="correo.mxcompute.com"
fi;

record=`nslookup -type=TXT ${txtRecord} 8.8.8.8 | sed -n "s/^correo\.mxcompute\.com\stext\s=\s\(.*\) \(\W*all\)\s*\"/\1/p"`
extra=`nslookup -type=TXT ${txtRecord} 8.8.8.8 | sed -n "s/^correo\.mxcompute\.com\stext\s=\s\(.*\) \(\W*all\)\s*\"/\2/p"`


echo "Repace the SPF text record for: "
echo "---------------------------------------"
echo "$txtRecord.	IN      TXT       ${record} "'"'" "'"'"${spfRecord} ${extra}"'"'
echo "---------------------------------------"
echo ""

echo "Set the following reversed dns: "
echo "---------------------------------------"
echo  "${reversedDns}"
echo "---------------------------------------"


